import React from "react";
import Head from "next/head";
import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth"
import {GoogleAuthProvider} from "firebase/auth";
import {auth} from "../firebase/clientApp";

const uiConfig = {
    signInSuccessUrl: '/',
    signInOptions: [GoogleAuthProvider.PROVIDER_ID]
}


function SignInScreen() {
    return (
        <>
            <Head>
                <title>Next Firebase App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <StyledFirebaseAuth uiConfig={uiConfig} firebaseAuth={auth}/>
        </>
    )
}

export default SignInScreen
