import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {collection} from 'firebase/firestore';

import {useAuthState} from "react-firebase-hooks/auth";
import {useCollection} from "react-firebase-hooks/firestore";
import {auth, db} from "../firebase/clientApp";

export default function Home() {

    const [user, loading, error] = useAuthState(auth)

    const [votes, votesLoading, votesError] = useCollection(
        collection(db, 'votes')
    )

    console.log(user, loading, error)
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            {votesError && <strong>Error: {JSON.stringify(error)}</strong>}
            {votesLoading && <span>Collection: Loading...</span>}
            {votes && (
                <span>
            Collection:{' '}
                    {votes.docs.map((doc) => (
                        <React.Fragment key={doc.id}>
                            {JSON.stringify(doc.data())},{' '}
                        </React.Fragment>
                    ))}
          </span>
            )}


        </div>
    )
}
