import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useAuthState} from "react-firebase-hooks/auth";
import {auth} from "../firebase/clientApp";

export default function Home() {

    const [user, loading, error] = useAuthState(auth)

    console.log(user, loading, error)
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>


        </div>
    )
}
